---
name: Empty role-icingaweb2
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - roles/icingaweb2/**
      - molecule/role-icingaweb2/**
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'

jobs:
  icingaweb2-ansible-latest:
    runs-on: ubuntu-latest

    env:
      COLLECTION_NAMESPACE: icinga
      COLLECTION_NAME: icinga

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        distro: [ubuntu2204]
        python: ['3.10']
        ansible: ['2.16.2']
        scenario: [role-icingaweb2]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies ansible
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test-${{ matrix.ansible }}.txt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: |
          ansible --version
          molecule --version
          molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
